openconfig/lemming

- .github/workflows/go.yml
- .github/workflows/linter.yml
This adds go linting and go test / build workflows
> Add ci / linter workflow

- go.mod
- go.sum
- lemming.go
- lemming_test.go
Add more logging so that the server state is easy to see in logs
Add unittest for stop
> Fix Tsan issue with lemming_test

- dataplane/main/main.go
- dataplane/server.go
server is too generic of a name.
> Move dataplane/server package -> dataplane

- sysrib/main/main.go
- sysrib/server.go
- sysrib/server_test.go
I didn't want to change testing since the dataplane API is still in
development. So I created another layer -- in order to keep the test
unchanged.
> Integrate sysrib with dataplane

- gnmi/fakedevice/fakedevice.go
- gnmi/fakedevice/gobgp.go
- gnmi/fakedevice/interface.go
Need to use resolved pathstructs
> Fix ygnmi path structs

- dataplane/forwarding/fwd.go
* implement  gRPC server
* remove logging
> Misc cleanups to fwd.go

- dataplane/server.go
- gnmi/gnmiclient/client.go
- lemming.go
- sysrib/server.go
- sysrib/server_test.go
removed viper calls and replaced using parameters.
> Clean up sysrib/refactor gnmiclient

- sysrib/server.go
- sysrib/server_test.go
- sysrib/sysrib.go
> Always process each prefix when programming routes

- gnmi/fakedevice/fakedevice.go
- lemming.go
syslog is removed since that's also a demo task.
> Convert to ygnmi tasks apart from BGP

- gnmi/gnmiclient/client.go
- gnmi/reconciler/reconciler.go
- gnmi/reconciler/reconciler_test.go
this should simplify making simple reconcilers
> Add reconciler builders

- gnmi/cache.go
- gnmi/fakedevice/fakedevice.go
- gnmi/gnmi.go
- gnmi/gnmi_test.go
> Use context metadata to allow state updates to specify SetRequest timestamp.

- gnmi/yang/openconfig-bgp-gue.yang
Per feedback from some OpenConfig members.
> Update YANG desc for BGP GUE

- operator/api/lemming/v1alpha1/lemming_types.go
I'll implement the logic for this later, just need it for a kne PR
> Add pending phase

- Makefile
- integration_tests/binding/binding.go
This will help debugging CI failures
> Stream command output when deploying topology

- Makefile
- bgp/gobgp.go
- integration_tests/onedut_oneotg_tests/bgp_route_propagation/bgp_route_propagation_test.go
This is copied from https://github.com/openconfig/featureprofiles/blob/main/feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go except the IPv6 stuff are removed.
> Add BGP Route Propagation Test

- integration_tests/twodut_oneotg_tests/bgp_triggered_gue/bgp_triggered_gue_test.go
- sysrib/server.go
- sysrib/sysrib.go
Configuration only involves changing AS numbers to be the same.
> Have lemmings using iBGP to exchange routes in GUE test

- sysrib/sysrib.go
- sysrib/sysrib_test.go
It already supports it by coincidence.
> Add v4-mapped-v6 unit tests for sysrib_test.go

- cmd/lemming/lemming.go
- gnmi/gnmi.go
- gnmi/gnmi_test.go
- gnsi/pathz/pathz.go
- lemming.go
Instead of a flag, don't check auth until a policy is installed
> Integrate pathz with set

- gribi/gribi.go
- lemming.go
This is a temporary solution since it doesn't handle deletes.
This would support integrating lemming into gribigo
> Update AFT paths as a gRIBI hook function

- dataplane/handlers/interface.go
- dataplane/internal/kernel/kernel.go
- dataplane/internal/kernel/kerneltest/kernel.go
- dataplane/internal/kernel/kerneltest/kernel_test.go
this will be used for testing some dataplane features in a follow up PR
> Create a kernel fake for handling interfaces

- gnmi/gnmi.go
- gnsi/acltrie/trie.go
- gnsi/acltrie/trie_test.go
- go.mod
- go.sum
- integration_tests/onedut_tests/gnsi_test/gnsi_test.go
- internal/binding/binding.go
- operator/config/manager/kustomization.yaml
* integration test for read/write gNMI with pathz
* fix set rollback when using auth
* allow policies on root
* update operator image version
* flag to skip preventing multiple tests from running on the same dut at the same time
> Integration test for gNSI pathz

- gnmi/gnmi_bench_test.go
```
BenchmarkGNMISet/config_replace-12                     2        1360487239 ns/op
BenchmarkGNMISet/state_replace-12                      2        1249092750 ns/op
BenchmarkGNMISet/config_update-12                      1        7883432860 ns/op
BenchmarkGNMISet/state_update-12                      61          20531426 ns/op
BenchmarkGNMISet/config_replace_and_delete-12                  1        1994916012 ns/op
BenchmarkGNMISet/state_replace_and_delete-12                   1        1479546999 ns/op
```
> Add gNMI benchmark test

- gnmi/gnmi_test.go
- go.mod
- go.sum
> Refactor ygnmi test

- gnmi/gnmi_test.go
It looks like this could be a useful feature for some folks so adding more coverage.
> Add a few more gNMI validation tests

- .bazelrc
- dataplane/internal/engine/engine.go
- integration_tests/onedut_oneotg_tests/topology.pb.txt
- integration_tests/onedut_tests/topology.pb.txt
- integration_tests/twodut_oneotg_tests/topology.pb.txt
- integration_tests/twodut_tests/topology.pb.txt
- internal/binding/BUILD.bazel
- internal/binding/binding.go
* "LEMMING" model to topologies
* change lemming bind to kne as library instead of cli
* enable incompatible strict action env to improve bazel caching
> Add model to topos and remove execs of kne_cli

- bgp/gobgp.go
- bgp/ocgobgp.go
Resolve the existing TODO and improve the comments.
> Refactor BGP Policy conversion code

- dataplane/standalone/apigen/apigen.go
- dataplane/standalone/apigen/ccgen.go
- dataplane/standalone/apigen/protogen.go
* Generate all types that aren't attributes or message in common file
* Add entry types and fix some of the hand crafted types
* Correctly handle all list types.
> SAI proto gen part 3

- bgp/gobgp.go
- bgp/ocgobgp.go
- bgp/tests/local_tests/BUILD
- bgp/tests/local_tests/community_set_test.go
- bgp/tests/local_tests/set_attributes_test.go
Also populate community-sets in the RIB
> Add tests for BGP communities with MatchOptions ADD/ALL

- bgp/BUILD
- bgp/config.go
- bgp/gobgp.go
- bgp/tests/local_tests/policy_test.go
- lemming.go
No logic change:
* Moved config conversion logic to new file.
* Factored out and reordered functions for top-down reading order.
Next PR: https://github.com/openconfig/lemming/pull/253
> Refactor bgp logic

- bgp/gobgp.go
The current BGP reset via clearing gNMI config is not working. This is because the current declarative config functionality from GoBGP cannot handle either 1) stopping the BGP server and then re-starting, nor 2) the clean-up of a GoBGP server when instantiating a new one.
In 1) it doesn't stop the Zebra client, and so reports an error that "zebra is already connected" upon restart. This is potentially fixable by a patch to GoBGP.
In 2) if stopped, then there is an infinite loop that is leaked (server is started with `go bgpServer.Serve()`): https://github.com/osrg/gobgp/blob/5f01c74a5b067aa05f6aa05610f2cc3bfebc4ab3/pkg/server/server.go#L435, so if we then instantiate a new GoBGP server, then we have a bunch of long-running goroutines with infinite loops.
To partially support reset, this …
> Partial support for BGP Reset by never stopping the GoBGP server.

- gnmi/gnmi.go
Between this PR and https://github.com/openconfig/lemming/pull/255 there are 10 passed presubmits, whereas the previous PRs (e.g. https://github.com/openconfig/lemming/pull/250, https://github.com/openconfig/lemming/pull/251) failed frequently.
This doesn't prove it fixes it since I'm not sure **why** this change would fix it, as all Sets are supposed to be synchronous.
> Maybe fix for "update is stale"

- .github/workflows/buildtest.yml
the bazel cache is quite large, so only create on the main branch, but create it for every push
> Update build action for better caching

- dataplane/standalone/saiserver/attrmgr/BUILD
- dataplane/standalone/saiserver/attrmgr/attrmgr.go
- dataplane/standalone/saiserver/attrmgr/attrmgr_test.go
* Create attrmgr that store the proto attributes from Create and Set RPC and fills them in Get RPCs.
> Implement SAI attribute tracking in go

- dataplane/internal/engine/engine.go
I plan on refactoring this package soon, so no tests for now
> Support for modifying aggregate interfaces

- dataplane/standalone/entrypoint.cc
- dataplane/standalone/lucius/BUILD
- dataplane/standalone/lucius/lucius.go
- dataplane/standalone/saiserver/BUILD
- dataplane/standalone/saiserver/attrmgr/BUILD
- dataplane/standalone/saiserver/attrmgr/attrmgr.go
- dataplane/standalone/saiserver/attrmgr/attrmgr_test.go
- dataplane/standalone/saiserver/saiserver.go
- dataplane/standalone/saiserver/switch.go
- dataplane/standalone/saiserver/switch_test.go
* fixed populating fields
* a createswitch
> CreateSwitch and a few bug fixes

- bgp/gobgp.go
- integration_tests/dut_policy_tests/prefix_set/prefix_set_test.go
- policytest/BUILD
- policytest/policytest.go
- sysrib/server_test.go
- sysrib/sysrib_test.go
Had trouble getting code de-duped using generics between V4 and V6, not sure if there is a good way to do it.
> Support IPv6 Prefix Sets

- dataplane/standalone/saiserver/attrmgr/BUILD
- dataplane/standalone/saiserver/attrmgr/attrmgr.go
- dataplane/standalone/saiserver/attrmgr/attrmgr_test.go
- dataplane/standalone/saiserver/ports_test.go
* Return error is attribute isn't set
* Support empty vs nil lists
* Empty list: value is set  and is empty
* Nil: value is unset
> Support empty vs nil lists and error for unset attrs

- bgp/config_test.go
- bgp/ocgobgp.go
- bgp/tests/local_tests/community_set_test.go
Qualify each name with policy name to make them globally unique for GoBGP.
> Allow Same Statement Names across Policies

- bgp/tests/local_tests/prefix_set_test.go
- gnmi/gnmi_test.go
Next PR I will change `, true, false, false` to a table-driven test so it's easier to read.
> Dedup gNMI test code and add extra prefix-set test cases

- dataplane/forwarding/fwdtable/flow/flow.go
- dataplane/standalone/saiserver/BUILD
- dataplane/standalone/saiserver/acl.go
- dataplane/standalone/saiserver/saiserver.go
- dataplane/standalone/saiserver/switch.go
- dataplane/standalone/saiserver/switch_test.go
These tables aren't used anywhere yet, coming in future PR
Note: i will add unit tests one the tables are integrated in the forwarding pipeline as there may be some impl changes
> Initial support of acl RPCs

- dataplane/standalone/saiserver/routing.go
With the change, i was able to get the e2e test work.
Will add missing features + UT in next PR
> Implement bulk neigh API

- sysrib/connected.go
- sysrib/server.go
- sysrib/server_test.go
- sysrib/static_connected_test.go
- sysrib/zapi_test.go
Failing due to flakes. Attempted fix for flakes at https://github.com/openconfig/lemming/pull/307
> Connected route deletion

- gnmi/collector.go
- gnmi/gnmi.go
- sysrib/zapi.go
- sysrib/zapi_test.go
Also add debugging message for when "update is stale" happens again.
> Speed-up ZServer tests and set Notification timestamp closer to update location.

- bgp/BUILD
- bgp/config.go
- bgp/config_test.go
- bgp/gobgp.go
- bgp/ocgobgp.go
- go.mod
- go.sum
- repositories.bzl
Still one more PR that requires merging from upstream before removal of fork. This verifies that newly merged PRs from upstream work.
> Update to latest version of GoBGP.

- dataplane/forwarding/fwdconfig/BUILD
- dataplane/forwarding/fwdconfig/action.go
- dataplane/forwarding/fwdconfig/packet.go
- dataplane/forwarding/fwdconfig/table.go
- dataplane/standalone/saiserver/hostif.go
- dataplane/standalone/saiserver/routing.go
- dataplane/standalone/saiserver/routing_test.go
- dataplane/standalone/saiserver/switch.go
Add support for the hostif trap api.
Add more builders
In followup PRs.
* Add tests 
* Integrate into pipeline
> Add initial support for hostif traps

- dataplane/standalone/apigen/ccgen/ccgen.go
- dataplane/standalone/sai/hostif.cc
Plan for a longer term in this in works that doesn't make assumption of about interface naming
> Quick fix for hostif index calculation

- dataplane/forwarding/fwdaction/actions/mirror_test.go
- dataplane/forwarding/fwdaction/mock_fwdport/mock.go
- dataplane/forwarding/fwdport/port.go
- dataplane/forwarding/fwdport/port_test.go
- dataplane/forwarding/fwdport/ports/cpu.go
- dataplane/forwarding/fwdport/ports/cpu_test.go
- dataplane/forwarding/fwdport/ports/fake.go
- dataplane/forwarding/fwdport/ports/genetlink.go
- dataplane/forwarding/fwdport/ports/group.go
- dataplane/forwarding/fwdport/ports/kernel.go
- dataplane/forwarding/fwdport/ports/tap.go
- dataplane/internal/engine/engine.go
- dataplane/standalone/packetio/cpusink/cpusink.go
- dataplane/standalone/packetio/main.go
- dataplane/standalone/saiserver/BUILD
- dataplane/standalone/saiserver/hostif.go
- dataplane/standalone/saiserver/hostif_test.go
- dataplane/standalone/saiserver/ports.go
- dataplane/standalone/saiserver/routing.go
- dataplane/standalone/saiserver/saiserver.go
- dataplane/standalone/saiserver/switch.go
- dataplane/standalone/saiserver/switch_test.go
* CPU port only outputs some packets over gRPC.
* Fixed initialized order
* Support VRF that's not 0
> Misc packetio fixes

- gnmi/gnmi.go
Follow-up from https://github.com/openconfig/lemming/issues/263#issuecomment-1874642307
> Add comment to gnmi.go to suggest using gRPC interceptor when creating grpc.Server object.

- integration_tests/twodut_oneotg_tests/bgp_triggered_gue/bgp_triggered_gue_test.go
- sysrib/sysrib.go
There could be vendors/others reviewing this.
> Clean up some comments related to BGP-triggered GUE.

- dataplane/saiserver/BUILD
- dataplane/saiserver/l2.go
- dataplane/saiserver/saiserver.go
- dataplane/saiserver/switch.go
Code skeleton for L2MC and L2MCGroup.
> Add layer2 multicast and multicast group servers.

- operator/controllers/lemming_controller.go
didn't mean to include change earlier
> include app and topo labels if missing

- gnmi/gnmi.go
- internal/telemetry/BUILD
- internal/telemetry/telemetry.go
> Fix target handling

- fault/BUILD
- fault/client.go
- fault/fault.go
- fault/fault_test.go
- integration_tests/onedut_tests/fault/BUILD
- integration_tests/onedut_tests/fault/fault_test.go
- integration_tests/onedut_tests/topology.pb.txt
unit tests and more cleanup in follow up PR
> basic fault client and sample test

- dataplane/dplanerc/BUILD
- dataplane/dplanerc/interface.go
- dataplane/dplanerc/routes.go
- integration_tests/onedut_oneotg_tests/traffic_test/traffic_test.go
- integration_tests/onedut_oneotg_tests/vlan_subintf/BUILD
- integration_tests/onedut_oneotg_tests/vlan_subintf/vlan_subintf_test.go
- sysrib/connected.go
- sysrib/server.go
There will more changes to vlan vrf, this just the initial implementation
> Make most routing support vrfs and subinterfaces

- gnmi/fakedevice/BUILD
- gnmi/fakedevice/fakedevice.go
- gnoi/gnoi.go
- gnoi/gnoi_test.go
- lemming.go
- Adds mock system process management with signal handling
- Implements process restart logic with PID regeneration
- Validates process lifecycle and state persistence
> Implement kill process functionality

- gnmi/fakedevice/fakedevice.go
- gnoi/gnoi.go
- gnoi/gnoi_test.go
- Added more mock processes for broader testing.
- Changed PID generation to prevent immediate reuse after restart.
- Fix reboot context to prevent premature cancellation.
> Fix: Support component path flexibility for Arista

- README.md
Add a new line before code block for proper rendering in sites not limited to Github
> Update README.md: Add a new line before code block
