gnmi/gnmi.go
lemming.go
lemming_test.go

ports can be allocated before trying to use the device

refactor lemming to take a net listener this makes testing easiler since

---

README.md

Minor cleanups in the lemming README.
```
* (M) README.md
- reference a generically "OpenConfig compliant" device rather than a particular
operator's requirements.
```

Make README generic.

---

gnmi/gnmit/gnmit.go
gnmi/gnmit/gnmit_test.go

```
* (M) gnmi/gnmit/gnmit.go
- Modify gnmit to not create a new gRPC server, allowing it to
be bound to an existing server.
```
The current gnmit implementation assumes that it can own the gNMI server, which
means it cannot be easily bound to a different gRPC server that already exists.
This PR creates a `NewServer` mechanism that can create the server and return it
such that it can be run on an existing port.

Refactor gnmit.New to allow gnmit to be bound to existing server.

---

gnmi/gnmit/datastore.go
gnmi/gnmit/gnmit.go
gnmi/testagent/testagent.go
gnmi/testagentlocal/interface.go

Also fix testagentlocal which was continuously updating the applied state even when there were no updates. Alas, easy to get things wrong without a test.

Allow the datastore to update state values by calling GnmiUpdate directly.

---

gnmi/fakedevice/fakedevice.go
gnmi/fakedevice/gobgp.go
gnmi/gnmi.go
gnmi/gnmit/datastore.go
gnmi/gnmit/gnmit.go
gnmi/gnmit/gnmit_test.go
go.mod
go.sum
integration_tests/twodut_tests/bgp_establish_test.go
lemming.go
sysrib/server.go
sysrib/server_test.go

Also fixed the following:
* Fixed TODO for op state datastore service. It now behaves the same way as the config datastore.
* Removed the Task interface. The boilerplate savings are substantial.
* Imported latest version of ygot to simply datastore's unmarshalling code.

Convert ygnmi GoBGP task

---

gnmi/fakedevice/fakedevice.go
gnmi/fakedevice/gobgp.go
gnmi/gnmiclient/cache.go
gnmi/gnmiclient/client.go
gnmi/gnmit/gnmit_test.go
lemming.go
sysrib/server.go
sysrib/server_test.go

Refactored existing code to use the same pattern as the dataplane for using this helper.

Only use CacheClient as gNMI client helper.

---

gnmi/gnmi.go
gnmi/gnmit/collector.go
gnmi/gnmit/gnmit.go
gnmi/gnmit/gnmit_test.go

gnmit.New() is the function to call. I didn't remove gnmi/ since as it is it is agnostic to which generated ygot GoStruct it's using, and gnmi/ calls `oc.Schema()` to specify that. This way other repos can use it too.

Refactor gnmit

---

dataplane/handlers/interface.go
dataplane/internal/engine/port.go
dataplane/internal/engine/table.go
go.mod
go.sum
integration_tests/traffic_test.go
proto/forwarding/forwarding_common.proto
proto/forwarding/forwarding_service.proto

Currently this is done by polling the forwarding service once per second. Ideally the forwarding service supports streaming the counter values, but I think this is good enough for now. Added a TODO in the forwarding service definition.
For some reason I had to downgrade Ondatra for the traffic test to work (I think the error was target "lemming" not found) -- Could it be due to https://github.com/openconfig/ondatra/commit/3338c3259dd8419b059443cadd238841a2472015#diff-14271c87af5568921ff5c49b376f4d9b0233c11ab49660ec5f6bfd0a1f7174c4 ?

Query and Update Packet Counters (in-pkt/out-pkt)

---

integration_tests/twodut_oneotg_tests/bgp_redistribution_v6/bgp_redistribution_v6_test.go

This is just a copy of the BGP redist test with IPv6 conversion. Static routes are used instead of gRIBI since gRIBI doesn't support IPv6 right now.

Add IPv6 BGP Route redistribution test

---

cmd/lemming/lemming.go
lemming.go
lemming_test.go
operator/config/samples/lemming_v1alpha1_lemming.yaml

- gNMI/gNOI/gNSI on one port
- gRIBI on another
- P4RT on another
These were intended to run on different ports.
NOTE: There is actually a hack in here where I made the gRIBI service actually register in the same place as gNMI/gNOI. This is to deal with the fact that KNE doesn't have lemming registered with the right port. This can be changed after that is done.

Change lemming's g* services to run on different ports per intent.

---

bgp/gobgp.go
bgp/local_tests/session_establish_test.go
bgp/local_tests/ygnmi_test.go
cmd/lemming/lemming.go
go.mod
go.sum
lemming.go

Just pretty much copying the integration_test's BGP session establishment test over.
* Added a ygnmi test library similar to ondatra's
* Added ability to specify local BGP listen port since OC doesn't have that knob.

Add local BGP test

---

bgp/gobgp.go
bgp/local_tests/route_propagation_test.go
bgp/local_tests/session_establish_test.go

* Also refactor existing code to create lemmings and establishing sessions to allow for multiple sessions to be established in different ways.
* BGPDevice -> DeviceSpec to more fully specify parameters when creating lemming instance.

Populate Adj-RIBs

---

Makefile
bgp/gobgp.go

Otherwise the BGP thread only listens on a single port and sessions can't be established with incoming connections from other ports.
This fixes the BGP integration tests.

Only set localAddress when routerID is loopback.

---

dataplane/standalone/apigen/BUILD
dataplane/standalone/apigen/apigen.go
dataplane/standalone/apigen/xml.go
go.mod
go.sum
repositories.bzl

* Support for parsing SAI doxygen xml
* Initial templates and generation logic
Note: this is just part1
* Some types are not yet generated. (enums, compound types_
* RPCs will be need to handle object ids.

Initial protobuf generator for SAI

---

dataplane/standalone/apigen/BUILD
dataplane/standalone/apigen/apigen.go
dataplane/standalone/apigen/ccgen.go
dataplane/standalone/apigen/protogen.go
dataplane/standalone/apigen/xml.go

* Split code in 3 files: 
* apigen: parses the ast and built the struct
* protogen: generates proto code
* ccgen: generates cc code
* generated all enum types
* hand crafted structs for complex types

Improvements to proto generator 

---

lemming.go
lemming_test.go

```
* (M) lemming(_test)?.go
- Today if a user does `if err := lemming.Stop(); err != nil { ... }`
then they will report a failure even if there were no errors
because the slice returned is non-nil.
```

Ensure that lemming.Stop() returns a nil error.

---

bgp/gobgp.go
bgp/tests/local_tests/policy_test.go
bgp/tests/local_tests/session_establish_test.go
bgp/tests/local_tests/ygnmi_test.go
dataplane/forwarding/util/stats/stats.go

Need to check routes after reset.
Cannot use regular `Await` because need t.Fatal to be called in main test goroutine.

Fix <PolicyTest>/installPolicyAfterRoutes

---

policytest/policytest.go

Recent failures are at BGP session establishment, which is the place of highest CPU usage.

Increase Await timeout for BGP policy test

---

.github/workflows/buildtest.yml

Since not all build targets have tests, the build cache is more complete than the test cache

Cache build and test separately

---

bgp/gobgp.go

Aside from RoutingPolicy since unsupported leaves will be populated as well. Added TODO for it.

Populate applied state for BGP

---

bgp/tests/local_tests/community_set_test.go
bgp/tests/local_tests/policy_test.go
bgp/tests/local_tests/prefix_set_test.go
bgp/tests/local_tests/route_propagation_test.go
bgp/tests/local_tests/set_attributes_test.go

Previously it's depending on policy to be configured prior to BGP session establishment.
Don't depend on this, and instead on `Await` for the policy to be configured.

Change BGP tests to wait for policy state

---

gnmi/BUILD
gnmi/collector.go
gnmi/gnmi.go
gnmi/gnmi_test.go
lemming.go
repositories.bzl

* Auto-populate Target when doing gNMI requests
* Auto-remove Target when responding to gNMI SubscribeRequest that didn't have prefix populated: https://www.openconfig.net/docs/gnmi/gnmi-specification/#2221-path-target
Resolves #263

Don't require Target when doing gNMI requests

---

bgp/tests/local_tests/route_propagation_test.go
sysrib/server.go
sysrib/server_zapi.go
sysrib/zapi.go
sysrib/zapi_test.go

* RedistributeDel non-connected routes from RIB to ZAPI clients.
* Delete routes from RIB when ZAPI RouteDelete message is received.

Support BGP Route Deletion

---

integration_tests/onedut_oneotg_tests/aggregate/aggregate_test.go
integration_tests/onedut_oneotg_tests/bgp_route_propagation/bgp_route_propagation_test.go
integration_tests/onedut_oneotg_tests/static_route_test/static_route_traffic_test.go
integration_tests/onedut_oneotg_tests/traffic_test/traffic_test.go
integration_tests/twodut_oneotg_tests/bgp_redistribution/bgp_redistribution_test.go
integration_tests/twodut_oneotg_tests/bgp_triggered_gue/bgp_triggered_gue_test.go
internal/attrs/attrs.go

This prepares lemming for the latest version of gosnappi, in which the SetChoice methods are removed.

Remove unnecessary calls to gosnappi SetChoice

---

integration_tests/twodut_oneotg_tests/bgp_triggered_gue/bgp_triggered_gue_test.go
internal/debug/debug.go
sysrib/BUILD
sysrib/server.go
sysrib/server_zapi.go
sysrib/util.go
sysrib/zapi.go
sysrib/zapi_test.go

BGP routes distributed from GoBGP -> sysRIB must not be redistributed back into GoBGP. Otherwise GoBGP thinks it's a locally-originated route and will prefer it over all other routes, and any BGP path attributes are also erased in the process.
BGP-triggered GUE had to be tweaked because OTG tears down the BGP session on PushConfig, so every instance of the traffic test has to wait for the BGP session to re-establish first. This issue was masked by the above bug in sysRIB.

Avoid redistributing BGP routes back to BGP speaker in a loop.

---

dataplane/dplanerc/routes.go
dataplane/saiserver/routing.go
dataplane/saiserver/routing_test.go

Implements RemoveNextHopGroup() and RemoveNextHopGroupMember().

Implement the removal of NextHopGroup and NextHopGroupMember.

---

.github/workflows/generatedcode.yml
dataplane/BUILD
dataplane/saiserver/ports.go
dataplane/saiserver/routing.go
dataplane/saiserver/routing_test.go
dataplane/saiserver/switch.go
dataplane/saiserver/tunnel.go

Initial tun term impl

---

bgp/config_test.go
bgp/ocgobgp.go
bgp/tests/local_tests/BUILD
bgp/tests/local_tests/community_count_test.go
go.mod
go.sum
repositories.bzl

New paths supported:
* /routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/community-count/config/operator
* /routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/community-count/config/value
Waiting for https://github.com/osrg/gobgp/pull/2792

Support Community Count BGP Policy Condition

---

gnmi/fakedevice/BUILD
gnmi/fakedevice/fakedevice.go
gnoi/BUILD
gnoi/gnoi.go
gnoi/gnoi_test.go
go.mod
integration_tests/onedut_tests/complete_chassis_reboot/BUILD
integration_tests/onedut_tests/complete_chassis_reboot/complete_chassis_reboot_test.go
lemming.go
lemming_test.go

* Populate minimum paths in CHASSIS component type to have `gNOI-3.1: Complete Chassis Reboot` pass.
* For Reboot and CancelReboot, only the delay parameter is supported.
* Re-enabled fakedevice.NewCurrentTimeTask()
The Reboot/CancelReboot behaviour is taken from the comments in https://github.com/openconfig/gnoi/blob/main/system/system.proto. The implementation uses non-straightforward concurrency for cleaning-up concurrency signals, but I didn't see another way to do this for now since the spawned goroutine has a limited lifetime.

Support Minimum gNOI Reboot and CancelReboot Functionality

---

integration_tests/onedut_oneotg_tests/bgp_route_propagation/bgp_route_propagation_test.go

Currently it's failing because the `Await` check before the `Get` wait for **any** prefix rather than the prefix `Get` is looking for. This makes some of the checks fail intermittently when multiple prefixes are checked at the same time.

Make BGP prefix checking less flaky

---

BUILD
go.mod
go.sum
gribi/gribi.go
lemming.go
repositories.bzl

```
* (M) lemming.go
* (M) gribi/gribi.go
- for some behaviours, there is a need to change the underlying RIB functionality
in the gRIBI server as a lemming is created. this change plumbs some options
through to allow lemmings to be created using this method.
```

Add support for plumbing gRIBI server options through lemming.

---

sysrib/server.go
sysrib/server_test.go
sysrib/sysrib.go
sysrib/sysrib_test.go

```
* (M) sysrib/{server,server_test,sysrib,sysrib_test}.go
- Avoid infinite stack depth when a route recurses onto itself.
Previously, looking up a next-hop or next-hop interface would
not track the visited nodes, and hence infinite recursion could
occur. This PR adds tracking of these changes into the RIB
lookup to avoid this.
```

Address infinite loop when recursively resolving routes.

---

bgp/gobgp.go
bgp/tests/local_tests/BUILD
bgp/tests/local_tests/next_hop_attr_test.go
bgp/tests/local_tests/policy_test.go
policytest/definitions.go

The policy_tests.go file is updated to ignore that next-hop field when comparing attributes, so that previous test cases don't need to be rewritten.
The test case does not yet modify the attribute itself, as this feature is not yet supported.

Export NextHop in BGP attribute map

---

gribi/gribi.go

```
commit ebfc91c7200f6e3a41e3c4a73eadd115520383e2
Author: Rob Shakir <robjs@google.com>
Date:   Mon Jan 6 20:34:01 2025 +0000
Initialise the unimplemented server given that gRIBI is embedded.
* (M) gribi/gribi.go
- Ensure that the unimplemented server is initialised correctly.
```
This is required since gRPC added a check that the unimplemented servers
that are embedded as pointers must not be nil.

Update gRIBI server to accommodate gRPC changes.

---

gnoi/gnoi.go

I would like to add some logs for Lemming's reboot functionality for the ease of debugging

Add log statement to gnoi reboot for debugging
